Repository gustavosr98/petromiles, pull requests merged in 2020-08, with the labels that each got.

#9 ISSUE-044: Elimina pruebas de mas
  petromiles-backend/src/database/seeders/routing-number/routing-number.service.spec.ts
  petromiles-backend/src/modules/cron/controllers/cron.controller.spec.ts
  petromiles-backend/src/modules/cron/services/cron.service.spec.ts
  petromiles-backend/src/modules/example/example.controller.spec.ts
  petromiles-backend/src/modules/language/language.controller.spec.ts
  petromiles-backend/src/modules/language/language.service.spec.ts
  petromiles-backend/src/modules/language/poeditor/poeditor.service.spec.ts
  petromiles-backend/src/modules/management/controllers/management.controller.spec.ts
  petromiles-backend/src/modules/management/services/management.service.spec.ts
  petromiles-backend/src/modules/payment-provider/payment-provider.service.spec.ts
  petromiles-backend/src/modules/payment-provider/stripe/stripe.service.spec.ts
  petromiles-backend/src/modules/third-party-clients/controllers/third-party-administration.controller.spec.ts
  petromiles-backend/src/modules/third-party-clients/controllers/third-party-clients.controller.spec.ts
  petromiles-backend/src/modules/third-party-clients/services/csv.service.spec.ts
  petromiles-backend/src/modules/third-party-clients/services/third-party-clients.service.spec.ts
  petromiles-backend/src/modules/transaction/controllers/transaction.controller.spec.ts
  petromiles-backend/src/modules/user/controllers/user.controller.spec.ts
Labels: Bug important, QA

#2 FASE3-025: [E2E-TEST] Como cliente quiero comprar puntos
  petromiles-backend/package.json
  petromiles-backend/src/main.ts
  petromiles-frontend/cypress.json
  petromiles-frontend/cypress/integration/payments/buy-points.spec.js
  petromiles-frontend/package-lock.json
  petromiles-frontend/package.json
  petromiles-frontend/src/components/Auth/LoginForm.vue
  petromiles-frontend/src/components/Client/Dashboard/BuyPointsCard.vue
  petromiles-frontend/src/components/General/Modals/ErrorModal/ErrorModal.vue
  petromiles-frontend/src/components/General/Navigation/Navbar.vue
  petromiles-frontend/src/components/Payments/BuyPointsForm.vue
Labels: QA

#3 FASE3-005: [UNIT-TEST] Transaction Service
  petromiles-backend/package.json
  petromiles-backend/src/modules/transaction/services/transaction.service.spec.ts
Labels: QA

#4 FASE3-020: [UNIT-TEST] Payment Provider Service
  petromiles-backend/src/modules/payment-provider/payment-provider.service.spec.ts
Labels: QA

#5 FASE3-039: [UNIT-TEST] Stripe Service
  petromiles-backend/src/modules/payment-provider/stripe/stripe.service.spec.ts
Labels: QA

#1 FASE3-004: [UNIT-TEST] Bank Account Service
  petromiles-backend/src/modules/bank-account/controllers/bank-account.controller.ts
  petromiles-backend/src/modules/bank-account/services/bank-account.service.spec.ts
  petromiles-backend/src/modules/bank-account/services/bank-account.service.ts
Labels: QA

#11 FASE3-014: [UNIT-TEST] Third Party Clients Service
  petromiles-backend/src/modules/payments/services/payments.service.spec.ts
  petromiles-backend/src/modules/third-party-clients/services/third-party-clients.service.spec.ts
  petromiles-backend/src/modules/third-party-clients/services/third-party-clients.service.ts
Labels: QA

#20 FASE3-048: Agregar Google Analytics y reportes de pruebas de seguridad
  petromiles-frontend/package-lock.json
  petromiles-frontend/package.json
  petromiles-frontend/security_reports/petromiles_report_1.html
  petromiles-frontend/vue-analytics.js
Labels: Task

#15 FASE3-042: [E2E-TEST] Como cliente quiero registrar una cuenta de usuario en petromiles con el registro tradicional
  petromiles-backend/package-lock.json
  petromiles-frontend/cypress/integration/clients/register-user.spec.js
  petromiles-frontend/src/components/Auth/LoginForm.vue
  petromiles-frontend/src/components/Auth/SignUpForm.vue
  petromiles-frontend/src/components/General/Modals/ErrorModal/ErrorModal.vue
Labels: QA

#16 FASE3-043 [E2E-TEST] Como cliente quiero pagar la suscripcion de Membresia Premium
  petromiles-frontend/cypress/integration/payments/subscription-payment.spec.js
  petromiles-frontend/src/components/Client/Dashboard/MembershipCard.vue
  petromiles-frontend/src/components/General/Modals/ErrorModal/ErrorModal.vue
  petromiles-frontend/src/components/Users/Subscriptions/Purchase/SubscriptionPurchase.vue
  petromiles-frontend/src/components/Users/Subscriptions/UserSubscription.vue
Labels: QA

#27 ISSUE-048: Arregla detalle con LogRocket
  petromiles-frontend/src/components/General/Navigation/Navbar.vue
  petromiles-frontend/src/store/index.js
Labels: Bug important

#28 ISSUE 049: Detalle de ramas en Travis
  .travis.yml
Labels: Bug detail

#17 FASE3-044 [E2E-TEST] Como cliente quiero acceder al sistema con login no federado
  petromiles-backend/package-lock.json
  petromiles-frontend/cypress/integration/clients/login-user.spec.js
Labels: QA

#19 FASE3-045 [E2E-TEST] Como cliente quiero recuperar la contraseña de mi cuenta de usuario
  petromiles-frontend/cypress/integration/clients/recover-password.spec.js
  petromiles-frontend/src/components/Auth/LoginForm.vue
  petromiles-frontend/src/components/Auth/RecoverPassword.vue
  petromiles-frontend/src/components/Auth/SignUpForm.vue
  petromiles-frontend/src/components/General/Navigation/Navbar.vue
  petromiles-frontend/src/components/General/Snackbar/Snackbar.vue
Labels: QA

#23 FASE3-047 [E2E-TEST] Como cliente quiero poder cambiar la contraseña de mi cuenta de usuario
  petromiles-frontend/cypress/integration/clients/change-password.spec.js
  petromiles-frontend/src/components/Users/changePassword.vue
Labels: QA

#24 FASE3- 021: [UNIT-TEST] Suscription Service
  petromiles-backend/src/modules/suscription/service/suscription.service.spec.ts
  petromiles-backend/src/modules/suscription/service/suscription.service.ts
  petromiles-backend/src/modules/suscription/suscription.module.ts
Labels: QA

#26 FASE3-011: [UNIT-TEST] Language Service
  petromiles-backend/src/modules/language/language.service.spec.ts
Labels: QA

#25 ISSUE-047: Corrección de error en pruebas unitarias de StripeService en producción
  petromiles-backend/src/modules/payment-provider/stripe/stripe.service.spec.ts
Labels: Bug important

#30 FASE3-050: [E2E-TEST] (Backend) Obtener una transacción específica
  petromiles-backend/test/jest-e2e.json
  petromiles-backend/test/transaction.e2e-spec.ts
Labels: QA

#36 FASE3-055: [UNIT-TEST] SignUpForm (Front)
  .travis.yml
  petromiles-frontend/package.json
  petromiles-frontend/src/store/__mocks__/index.js
  petromiles-frontend/tests/unit/buyPointsForm.spec.js
  petromiles-frontend/tests/unit/exchangePointsForm.spec.js
  petromiles-frontend/tests/unit/loginForm.spec.js
  petromiles-frontend/tests/unit/signUpForm.spec.js
Labels: QA

#34 FASE3-001: [UNIT-TEST] Auth Service
  petromiles-backend/src/modules/auth/auth.service.spec.ts
  petromiles-backend/src/modules/auth/auth.service.ts
Labels: QA

#35 FASE3-006: [UNIT-TEST] State Transaction Service
  petromiles-backend/src/modules/transaction/services/mocks/state-transaction.mock.ts
  petromiles-backend/src/modules/transaction/services/state-transaction.service.spec.ts
  petromiles-backend/src/modules/transaction/services/state-transaction.service.ts
Labels: QA

#39 FASE3-017: [UNIT-TEST] Points Conversion Service
  petromiles-backend/src/modules/management/services/points-conversion.service.spec.ts
  petromiles-backend/src/modules/management/services/points-conversion.service.ts
Labels: QA

#40 FASE-052: [E2E-TEST] (Backend) Compra y retiro de puntos
  petromiles-backend/package-lock.json
  petromiles-backend/package.json
  petromiles-backend/src/modules/payments/controller/payments.controller.ts
  petromiles-backend/test/payments.e2e-spec.ts
  petromiles-backend/test/transaction.e2e-spec.ts
  petromiles-frontend/package-lock.json
Labels: QA

#32 FASE3-046 [E2E-TEST] Como cliente quiero actualizar la información de mi perfil de usuario
  petromiles-frontend/cypress/integration/clients/update-profile.spec.js
  petromiles-frontend/src/components/Users/UserDetail.vue
Labels: QA
